spring:
  application:
    name: spring-flyway

  datasource:
    url: jdbc:mysql://localhost:3306/school?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ghoo

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  flyway:
    enabled: true
    url: jdbc:mysql://localhost:3306/school?serverTimezone=UTC&characterEncoding=UTF-8
    user: root
    password: ghoo
    locations: classpath:db/migration
    baseline-on-migrate: true
    target: 3.5
